name:                AdventOfCode
version:             0.1.0.0
github:              "bionikspoon/HaskellAdventOfCode2019"
license:             MIT
author:              "Manu Phatak"
maintainer:          "bionikspoon@gmail.com"
copyright:           "2020 Manu Phatak"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bionikspoon/HaskellAdventOfCode2019#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers

library:
  source-dirs: src

tests:
  AdventOfCode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode
    - hspec-discover
    - hspec

build-tools:
 - implicit-hie
 - hpc-lcov