version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        auth:
          username: bionikspoon
          password: $DOCKERHUB_PASSWORD
    working_directory: /app
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve dependencies
          command: stack --no-terminal setup
      - run:
          name: Install executable
          command: stack --no-terminal install
      - run:
          name: Clean any cached coverage data
          command: rm -rfv $(stack --no-terminal path --local-hpc-root)
      - save_cache:
          name: Save Cache
          key: v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run:
          name: Run tests
          command: stack --no-terminal test --coverage
      - run:
          name: Generate lcov
          command: stack --no-terminal exec hpc-lcov
      - run:
          name: Publish coverage
          command: bash <(curl -s https://codecov.io/bash)
      # - run:
      #     name: Generate Coverage
      #     command: stack --no-terminal hpc report --all --destdir coverage


